### ISSUE TITLE
Untranslated Strings

### ISSUE THREAD

**Issue by smaragdus** [Misoni64T/simple-url-copy#3]
I noticed that in the [Chromium](https://chrome.google.com/webstore/detail/simple-url-copy-f/kmkdfdfknlkjbmgdenhpeckpdafojnfo) version extended by [yudukiak](https://github.com/yudukiak) [fork](https://github.com/yudukiak/simple-url-copy) there are several untranslated strings which appear in Japanese, screens:

**- extension pop-up:**

![Simple URL Copy  F  2 1 0 - 2021-05-14 - 002](https://user-images.githubusercontent.com/9025757/118189870-02f3a180-b44b-11eb-9792-7dad274eb641.png)

**- extension options - export:**

![Simple URL Copy  F  2 1 0 - 2021-05-14 - 005](https://user-images.githubusercontent.com/9025757/118189980-29194180-b44b-11eb-81d2-5d39ab82d2bb.png)

**- extension options - import:**

![Simple URL Copy  F  2 1 0 - 2021-05-14 - 008](https://user-images.githubusercontent.com/9025757/118190413-c3798500-b44b-11eb-8f2a-25ab4450baed.png)

These are minor strings yet it would be better if everything is translated in English.

**Comment by misonln41** [comment]
Option settings are originally added by yudukiak, so it isn't suitable for this repository.

**Comment by smaragdus** [comment]
@MISONLN41 

I knew this repository was not the right place to open this issue but the [fork](https://github.com/yudukiak/simple-url-copy) does not have issues and there is no way to contact the developer (@yudukiak) so I opened it here hoping that he/she would notice it.
